name: publish
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: publish
        run: |
          export PACKAGE_VERSION=`node -p "require('./package.json').version"`
          yarn version --new-version "$PACKAGE_VERSION"
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
