name: cicd
on: workflow_call

permissions:
  pull-requests: write

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: dependencies
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
