name: publish
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: troubleshoot
        run: |
          echo github.ref = ${{ github.ref }}
          echo github.head_ref = ${{ github.head_ref }}

      - name: verify tag version
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          # Verify package.json and tag name match
          TAG_VERSION=${GITHUB_REF#refs/*/}
          PACKAGE_VERSION=`node -p "require('./package.json').version"`
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "package.json/version does not equal the tag name"
            exit 1
          fi

      - name: publish
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          # Verify package.json and tag name match
          TAG_VERSION=${GITHUB_REF#refs/*/}
          PACKAGE_VERSION=`node -p "require('./package.json').version"`
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "package.json/version does not equal the tag name"
            exit 1
          fi

          # Now publish
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
